channels:
- defaults
- conda-forge
dependencies:
- MarkupSafe=3.0.2
- SecretStorage=3.3.3
- absl-py=2.1.0
- alabaster=1.0.0
- anyio=4.8.0
- asttokens=2.4.1
- attrs=24.2.0
- babel=2.17.0
- backcall=0.2.0
- beautifulsoup4=4.12.3
- bleach=6.2.0
- blinker=1.9.0
- cachecontrol=0.14.1
- certifi=2024.8.30
- cffi=1.17.1
- charset-normalizer=3.4.0
- cleo=2.1.0
- click=8.1.8
- colorama=0.4.6
- comm=0.2.2
- contourpy=1.3.1
- crashtest=0.4.1
- cryptography=44.0.0
- cycler=0.12.1
- dash-bootstrap-components=1.7.1
- dash-core-components=2.0.0
- dash-html-components=2.0.0
- dash-leaflet=1.0.15
- dash-table=5.0.0
- dash=2.18.2
- debugpy=1.8.8
- decorator=5.1.1
- defusedxml=0.7.1
- distlib=0.3.9
- docopt=0.6.2
- docutils=0.21.2
- dulwich=0.21.7
- executing=2.1.0
- filelock=3.16.1
- flask=3.0.3
- fonttools=4.55.0
- furo=2024.8.6
- geographiclib=2.0
- h11=0.14.0
- idna=3.10
- imagesize=1.4.1
- immutabledict=4.2.1
- importlib-metadata=8.6.1
- ipykernel=6.29.5
- itsdangerous=2.2.0
- jaraco.classes=3.4.0
- jedi=0.19.2
- jeepney=0.8.0
- jinja2=3.1.4
- jsonschema-specifications=2024.10.1
- jsonschema=4.23.0
- keyring=24.3.1
- kiwisolver=1.4.7
- matplotlib-inline=0.1.7
- matplotlib=3.8.4
- mistune=3.0.2
- mock=5.1.0
- more-itertools=10.5.0
- narwhals=1.26.0
- nbclient=0.10.1
- nbconvert=7.16.4
- nbformat=5.10.4
- nest-asyncio=1.6.0
- networkx=3.4.2
- numpy=2.2.1
- packaging=24.2
- pandas=2.2.3
- parso=0.8.4
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=11.0.0
- pip=25.0.1
- pkginfo=1.11.2
- platformdirs=4.3.6
- plotly=6.0.0
- poetry-core=1.9.1
- poetry-plugin-export=1.8.0
- poetry=1.8.4
- progressbar=2.5
- prompt-toolkit=3.0.48
- protobuf=5.26.1
- psutil=6.1.0
- ptyprocess=0.7.0
- pycparser=2.22
- pygments=2.18.0
- pyogrio=0.10.0
- pyparsing=3.2.0
- pyproj=3.7.0
- python-dateutil=2.9.0
- pytz=2024.2
- pyzmq=26.2.0
- rapidfuzz=3.10.1
- referencing=0.35.1
- requests-toolbelt=1.0.0
- requests=2.32.3
- retrying=1.3.4
- rpds-py=0.22.1
- setuptools=75.8.2
- shapely=2.0.7
- shellingham=1.5.4
- six=1.16.0
- sniffio=1.3.1
- snowballstemmer=2.2.0
- soupsieve=2.6
- sphinx-autobuild=2024.10.3
- sphinx-basic-ng=1.0.0
- sphinx=8.1.3
- sphinxcontrib-applehelp=2.0.0
- sphinxcontrib-devhelp=2.0.0
- sphinxcontrib-htmlhelp=2.1.0
- sphinxcontrib-jsmath=1.0.1
- sphinxcontrib-qthelp=2.0.0
- sphinxcontrib-serializinghtml=2.0.0
- starlette=0.45.3
- tabulate=0.9.0
- tinycss2=1.4.0
- tomli=2.2.1
- tomlkit=0.13.2
- tornado=6.4.1
- tqdm=4.67.1
- traitlets=5.14.3
- trove-classifiers=2024.10.21.16
- typing-extensions=4.12.2
- urllib3=2.2.3
- uvicorn=0.34.0
- virtualenv=20.28.0
- watchfiles=1.0.4
- wcwidth=0.2.13
- webencodings=0.5.1
- websockets=14.2
- werkzeug=3.0.6
- yarg=0.1.9
- zipp=3.21.0

- pip:
  - vrplib==1.5.1
  - utm==0.8.0
  - tzdata==2024.2
  - stack-data==0.6.3
  - pyvrp==0.10.1
  - pyproject-hooks==1.2.0
  - pure-eval==0.2.3
  - pipreqs==0.5.0
  - pandocfilters==1.5.1
  - ortools==9.11.4210
  - opencv-python==4.10.0.84
  - msgpack==1.1.0
  - jupyter-client==8.6.3
  - jupyter-core==5.7.2
  - jupyterlab-pygments==0.3.0
  - ipython==8.12.3
  - installer==0.7.0
  - fastjsonschema==2.21.0
  - build==1.2.2
  - alns==7.0.0

name: thesis 
